/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIStylingConsultation {
  'userPhoto' : ExternalBlob,
  'selectedStyles' : Array<HairstyleRecommendation>,
  'aiRecommendations' : Array<HairstyleRecommendation>,
}
export interface Appointment {
  'id' : string,
  'status' : AppointmentStatus,
  'aiStylingConsultation' : [] | [AIStylingConsultation],
  'userId' : Principal,
  'stylistId' : string,
  'note' : [] | [string],
  'createdBy' : [] | [Principal],
  'serviceId' : string,
  'dateTime' : Time,
  'salonId' : string,
}
export type AppointmentStatus = { 'canceled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface BookingStats {
  'canceled' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'confirmed' : bigint,
}
export interface BusinessDashboard {
  'reviews' : Array<Review>,
  'monthlySales' : Array<MonthlySalesData>,
  'monthlyBookings' : Array<MonthlyBookingStats>,
  'salonId' : string,
}
export interface CustomizationVariation {
  'previewImage' : [] | [ExternalBlob],
  'customizationDetails' : Array<string>,
  'variationName' : string,
  'description' : string,
}
export type ExternalBlob = Uint8Array;
export interface HairstyleRecommendation {
  'description' : string,
  'confidenceScore' : bigint,
  'image' : [] | [ExternalBlob],
  'styleName' : string,
}
export interface Location { 'latitude' : number, 'longitude' : number }
export interface MonthlyBookingStats {
  'month' : string,
  'totalBookings' : bigint,
}
export interface MonthlySalesData {
  'month' : string,
  'totalRevenueCents' : bigint,
  'transactionCount' : bigint,
}
export type RegistrationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Review {
  'id' : string,
  'reviewerName' : string,
  'comment' : string,
  'timestamp' : Time,
  'rating' : number,
  'salonId' : string,
}
export interface Sale {
  'id' : string,
  'amountCents' : bigint,
  'timestamp' : Time,
  'salonId' : string,
}
export interface Salon {
  'id' : string,
  'status' : RegistrationStatus,
  'latitude' : number,
  'verified' : boolean,
  'contactInfo' : string,
  'ownerName' : string,
  'name' : string,
  'longitude' : number,
  'address' : string,
}
export interface Service {
  'id' : string,
  'name' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'priceCents' : bigint,
}
export interface StylistProfile {
  'id' : string,
  'bio' : string,
  'name' : string,
  'specialties' : Array<string>,
  'photo' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addSale' : ActorMethod<[Sale], undefined>,
  'addSalon' : ActorMethod<[Salon], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'addStylist' : ActorMethod<[StylistProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<
    [string, string, string, Time, [] | [string]],
    string
  >,
  'cancelAppointment' : ActorMethod<[string], undefined>,
  'confirmAppointment' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'deleteStylist' : ActorMethod<[string], undefined>,
  'filterBookings' : ActorMethod<[string], Array<Appointment>>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllBookingStats' : ActorMethod<[null], BookingStats>,
  'getAllSalons' : ActorMethod<[], Array<Salon>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomizationRecommendations' : ActorMethod<
    [ExternalBlob],
    Array<CustomizationVariation>
  >,
  'getHairstylePhoto' : ActorMethod<[Principal], [] | [ExternalBlob]>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getMyHairstylePhoto' : ActorMethod<[], [] | [ExternalBlob]>,
  'getNearbySalons' : ActorMethod<[Location, number], Array<Salon>>,
  'getSalonDashboard' : ActorMethod<[string], BusinessDashboard>,
  'getSalonsByVerification' : ActorMethod<[boolean], Array<Salon>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getStylists' : ActorMethod<[], Array<StylistProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSalon' : ActorMethod<[Salon], undefined>,
  'updateService' : ActorMethod<[Service], undefined>,
  'updateStylist' : ActorMethod<[StylistProfile], undefined>,
  'uploadHairstylePhoto' : ActorMethod<[ExternalBlob], undefined>,
  'uploadStylingConsultation' : ActorMethod<
    [
      string,
      ExternalBlob,
      Array<HairstyleRecommendation>,
      Array<HairstyleRecommendation>,
    ],
    undefined
  >,
  'verifySalon' : ActorMethod<[string, boolean, RegistrationStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];