/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'id' : IDL.Text,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat8,
  'salonId' : IDL.Text,
});
export const Sale = IDL.Record({
  'id' : IDL.Text,
  'amountCents' : IDL.Nat,
  'timestamp' : Time,
  'salonId' : IDL.Text,
});
export const RegistrationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Salon = IDL.Record({
  'id' : IDL.Text,
  'status' : RegistrationStatus,
  'latitude' : IDL.Float64,
  'verified' : IDL.Bool,
  'contactInfo' : IDL.Text,
  'ownerName' : IDL.Text,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'priceCents' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StylistProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'specialties' : IDL.Vec(IDL.Text),
  'photo' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const HairstyleRecommendation = IDL.Record({
  'description' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'styleName' : IDL.Text,
});
export const AIStylingConsultation = IDL.Record({
  'userPhoto' : ExternalBlob,
  'selectedStyles' : IDL.Vec(HairstyleRecommendation),
  'aiRecommendations' : IDL.Vec(HairstyleRecommendation),
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : AppointmentStatus,
  'aiStylingConsultation' : IDL.Opt(AIStylingConsultation),
  'userId' : IDL.Principal,
  'stylistId' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'createdBy' : IDL.Opt(IDL.Principal),
  'serviceId' : IDL.Text,
  'dateTime' : Time,
  'salonId' : IDL.Text,
});
export const BookingStats = IDL.Record({
  'canceled' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'confirmed' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const CustomizationVariation = IDL.Record({
  'previewImage' : IDL.Opt(ExternalBlob),
  'customizationDetails' : IDL.Vec(IDL.Text),
  'variationName' : IDL.Text,
  'description' : IDL.Text,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const MonthlySalesData = IDL.Record({
  'month' : IDL.Text,
  'totalRevenueCents' : IDL.Nat,
  'transactionCount' : IDL.Nat,
});
export const MonthlyBookingStats = IDL.Record({
  'month' : IDL.Text,
  'totalBookings' : IDL.Nat,
});
export const BusinessDashboard = IDL.Record({
  'reviews' : IDL.Vec(Review),
  'monthlySales' : IDL.Vec(MonthlySalesData),
  'monthlyBookings' : IDL.Vec(MonthlyBookingStats),
  'salonId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'addSale' : IDL.Func([Sale], [], []),
  'addSalon' : IDL.Func([Salon], [], []),
  'addService' : IDL.Func([Service], [], []),
  'addStylist' : IDL.Func([StylistProfile], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'cancelAppointment' : IDL.Func([IDL.Text], [], []),
  'confirmAppointment' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Text], [], []),
  'deleteStylist' : IDL.Func([IDL.Text], [], []),
  'filterBookings' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], ['query']),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllBookingStats' : IDL.Func([IDL.Null], [BookingStats], ['query']),
  'getAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomizationRecommendations' : IDL.Func(
      [ExternalBlob],
      [IDL.Vec(CustomizationVariation)],
      [],
    ),
  'getHairstylePhoto' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getMyHairstylePhoto' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getNearbySalons' : IDL.Func(
      [Location, IDL.Float64],
      [IDL.Vec(Salon)],
      ['query'],
    ),
  'getSalonDashboard' : IDL.Func([IDL.Text], [BusinessDashboard], ['query']),
  'getSalonsByVerification' : IDL.Func([IDL.Bool], [IDL.Vec(Salon)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getStylists' : IDL.Func([], [IDL.Vec(StylistProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSalon' : IDL.Func([Salon], [], []),
  'updateService' : IDL.Func([Service], [], []),
  'updateStylist' : IDL.Func([StylistProfile], [], []),
  'uploadHairstylePhoto' : IDL.Func([ExternalBlob], [], []),
  'uploadStylingConsultation' : IDL.Func(
      [
        IDL.Text,
        ExternalBlob,
        IDL.Vec(HairstyleRecommendation),
        IDL.Vec(HairstyleRecommendation),
      ],
      [],
      [],
    ),
  'verifySalon' : IDL.Func([IDL.Text, IDL.Bool, RegistrationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'id' : IDL.Text,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat8,
    'salonId' : IDL.Text,
  });
  const Sale = IDL.Record({
    'id' : IDL.Text,
    'amountCents' : IDL.Nat,
    'timestamp' : Time,
    'salonId' : IDL.Text,
  });
  const RegistrationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Salon = IDL.Record({
    'id' : IDL.Text,
    'status' : RegistrationStatus,
    'latitude' : IDL.Float64,
    'verified' : IDL.Bool,
    'contactInfo' : IDL.Text,
    'ownerName' : IDL.Text,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'priceCents' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StylistProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'specialties' : IDL.Vec(IDL.Text),
    'photo' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const HairstyleRecommendation = IDL.Record({
    'description' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'styleName' : IDL.Text,
  });
  const AIStylingConsultation = IDL.Record({
    'userPhoto' : ExternalBlob,
    'selectedStyles' : IDL.Vec(HairstyleRecommendation),
    'aiRecommendations' : IDL.Vec(HairstyleRecommendation),
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : AppointmentStatus,
    'aiStylingConsultation' : IDL.Opt(AIStylingConsultation),
    'userId' : IDL.Principal,
    'stylistId' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'createdBy' : IDL.Opt(IDL.Principal),
    'serviceId' : IDL.Text,
    'dateTime' : Time,
    'salonId' : IDL.Text,
  });
  const BookingStats = IDL.Record({
    'canceled' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'confirmed' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const CustomizationVariation = IDL.Record({
    'previewImage' : IDL.Opt(ExternalBlob),
    'customizationDetails' : IDL.Vec(IDL.Text),
    'variationName' : IDL.Text,
    'description' : IDL.Text,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const MonthlySalesData = IDL.Record({
    'month' : IDL.Text,
    'totalRevenueCents' : IDL.Nat,
    'transactionCount' : IDL.Nat,
  });
  const MonthlyBookingStats = IDL.Record({
    'month' : IDL.Text,
    'totalBookings' : IDL.Nat,
  });
  const BusinessDashboard = IDL.Record({
    'reviews' : IDL.Vec(Review),
    'monthlySales' : IDL.Vec(MonthlySalesData),
    'monthlyBookings' : IDL.Vec(MonthlyBookingStats),
    'salonId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'addSale' : IDL.Func([Sale], [], []),
    'addSalon' : IDL.Func([Salon], [], []),
    'addService' : IDL.Func([Service], [], []),
    'addStylist' : IDL.Func([StylistProfile], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'cancelAppointment' : IDL.Func([IDL.Text], [], []),
    'confirmAppointment' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Text], [], []),
    'deleteStylist' : IDL.Func([IDL.Text], [], []),
    'filterBookings' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], ['query']),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllBookingStats' : IDL.Func([IDL.Null], [BookingStats], ['query']),
    'getAllSalons' : IDL.Func([], [IDL.Vec(Salon)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomizationRecommendations' : IDL.Func(
        [ExternalBlob],
        [IDL.Vec(CustomizationVariation)],
        [],
      ),
    'getHairstylePhoto' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getMyHairstylePhoto' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getNearbySalons' : IDL.Func(
        [Location, IDL.Float64],
        [IDL.Vec(Salon)],
        ['query'],
      ),
    'getSalonDashboard' : IDL.Func([IDL.Text], [BusinessDashboard], ['query']),
    'getSalonsByVerification' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Salon)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getStylists' : IDL.Func([], [IDL.Vec(StylistProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSalon' : IDL.Func([Salon], [], []),
    'updateService' : IDL.Func([Service], [], []),
    'updateStylist' : IDL.Func([StylistProfile], [], []),
    'uploadHairstylePhoto' : IDL.Func([ExternalBlob], [], []),
    'uploadStylingConsultation' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          IDL.Vec(HairstyleRecommendation),
          IDL.Vec(HairstyleRecommendation),
        ],
        [],
        [],
      ),
    'verifySalon' : IDL.Func([IDL.Text, IDL.Bool, RegistrationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };