/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    email?: string;
    phone?: string;
}
export interface StylistProfile {
    id: string;
    bio: string;
    name: string;
    specialties: Array<string>;
    photo?: ExternalBlob;
}
export interface Location {
    latitude: number;
    longitude: number;
}
export type Time = bigint;
export interface Salon {
    id: string;
    status: RegistrationStatus;
    latitude: number;
    verified: boolean;
    contactInfo: string;
    ownerName: string;
    name: string;
    longitude: number;
    address: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    id: string;
    name: string;
    description: string;
    durationMinutes: bigint;
    priceCents: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Sale {
    id: string;
    amountCents: bigint;
    timestamp: Time;
    salonId: string;
}
export interface MonthlySalesData {
    month: string;
    totalRevenueCents: bigint;
    transactionCount: bigint;
}
export interface BookingStats {
    canceled: bigint;
    pending: bigint;
    completed: bigint;
    confirmed: bigint;
}
export interface MonthlyBookingStats {
    month: string;
    totalBookings: bigint;
}
export interface CustomizationVariation {
    previewImage?: ExternalBlob;
    customizationDetails: Array<string>;
    variationName: string;
    description: string;
}
export interface BusinessDashboard {
    reviews: Array<Review>;
    monthlySales: Array<MonthlySalesData>;
    monthlyBookings: Array<MonthlyBookingStats>;
    salonId: string;
}
export interface AIStylingConsultation {
    userPhoto: ExternalBlob;
    selectedStyles: Array<HairstyleRecommendation>;
    aiRecommendations: Array<HairstyleRecommendation>;
}
export interface HairstyleRecommendation {
    description: string;
    confidenceScore: bigint;
    image?: ExternalBlob;
    styleName: string;
}
export interface Appointment {
    id: string;
    status: AppointmentStatus;
    aiStylingConsultation?: AIStylingConsultation;
    userId: Principal;
    stylistId: string;
    note?: string;
    createdBy?: Principal;
    serviceId: string;
    dateTime: Time;
    salonId: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Review {
    id: string;
    reviewerName: string;
    comment: string;
    timestamp: Time;
    rating: number;
    salonId: string;
}
export enum AppointmentStatus {
    canceled = "canceled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum RegistrationStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addReview(review: Review): Promise<void>;
    addSale(sale: Sale): Promise<void>;
    addSalon(salon: Salon): Promise<void>;
    addService(service: Service): Promise<void>;
    addStylist(stylist: StylistProfile): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(salonId: string, serviceId: string, stylistId: string, dateTime: Time, note: string | null): Promise<string>;
    cancelAppointment(appointmentId: string): Promise<void>;
    confirmAppointment(appointmentId: string): Promise<void>;
    deleteService(serviceId: string): Promise<void>;
    deleteStylist(stylistId: string): Promise<void>;
    filterBookings(search: string): Promise<Array<Appointment>>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllBookingStats(arg0: null): Promise<BookingStats>;
    getAllSalons(): Promise<Array<Salon>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomizationRecommendations(photo: ExternalBlob): Promise<Array<CustomizationVariation>>;
    getHairstylePhoto(user: Principal): Promise<ExternalBlob | null>;
    getMyAppointments(): Promise<Array<Appointment>>;
    getMyHairstylePhoto(): Promise<ExternalBlob | null>;
    getNearbySalons(location: Location, radiusKm: number): Promise<Array<Salon>>;
    getSalonDashboard(salonId: string): Promise<BusinessDashboard>;
    getSalonsByVerification(verified: boolean): Promise<Array<Salon>>;
    getServices(): Promise<Array<Service>>;
    getStylists(): Promise<Array<StylistProfile>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateSalon(salon: Salon): Promise<void>;
    updateService(service: Service): Promise<void>;
    updateStylist(stylist: StylistProfile): Promise<void>;
    uploadHairstylePhoto(externalBlob: ExternalBlob): Promise<void>;
    uploadStylingConsultation(appointmentId: string, userPhoto: ExternalBlob, selectedStyles: Array<HairstyleRecommendation>, aiRecommendations: Array<HairstyleRecommendation>): Promise<void>;
    verifySalon(salonId: string, verified: boolean, status: RegistrationStatus): Promise<void>;
}
import type { AIStylingConsultation as _AIStylingConsultation, Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, CustomizationVariation as _CustomizationVariation, ExternalBlob as _ExternalBlob, HairstyleRecommendation as _HairstyleRecommendation, RegistrationStatus as _RegistrationStatus, Salon as _Salon, StylistProfile as _StylistProfile, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addReview(arg0: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addSale(arg0: Sale): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0);
            return result;
        }
    }
    async addSalon(arg0: Salon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalon(to_candid_Salon_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalon(to_candid_Salon_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addService(arg0: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0);
            return result;
        }
    }
    async addStylist(arg0: StylistProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStylist(await to_candid_StylistProfile_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStylist(await to_candid_StylistProfile_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async cancelAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async confirmAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmAppointment(arg0);
            return result;
        }
    }
    async deleteService(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async deleteStylist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStylist(arg0);
            return result;
        }
    }
    async filterBookings(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterBookings(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterBookings(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookingStats(arg0: null): Promise<BookingStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingStats(arg0);
            return result;
        }
    }
    async getAllSalons(): Promise<Array<Salon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalons();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalons();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomizationRecommendations(arg0: ExternalBlob): Promise<Array<CustomizationVariation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomizationRecommendations(await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomizationRecommendations(await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHairstylePhoto(arg0: Principal): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHairstylePhoto(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHairstylePhoto(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppointments();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppointments();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyHairstylePhoto(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyHairstylePhoto();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyHairstylePhoto();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNearbySalons(arg0: Location, arg1: number): Promise<Array<Salon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbySalons(arg0, arg1);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbySalons(arg0, arg1);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalonDashboard(arg0: string): Promise<BusinessDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalonDashboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalonDashboard(arg0);
            return result;
        }
    }
    async getSalonsByVerification(arg0: boolean): Promise<Array<Salon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalonsByVerification(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalonsByVerification(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return result;
        }
    }
    async getStylists(): Promise<Array<StylistProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStylists();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStylists();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSalon(arg0: Salon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalon(to_candid_Salon_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalon(to_candid_Salon_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateService(arg0: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0);
            return result;
        }
    }
    async updateStylist(arg0: StylistProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStylist(await to_candid_StylistProfile_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStylist(await to_candid_StylistProfile_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadHairstylePhoto(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadHairstylePhoto(await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadHairstylePhoto(await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadStylingConsultation(arg0: string, arg1: ExternalBlob, arg2: Array<HairstyleRecommendation>, arg3: Array<HairstyleRecommendation>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadStylingConsultation(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), await to_candid_vec_n51(this._uploadFile, this._downloadFile, arg2), await to_candid_vec_n51(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadStylingConsultation(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), await to_candid_vec_n51(this._uploadFile, this._downloadFile, arg2), await to_candid_vec_n51(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async verifySalon(arg0: string, arg1: boolean, arg2: RegistrationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifySalon(arg0, arg1, to_candid_RegistrationStatus_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifySalon(arg0, arg1, to_candid_RegistrationStatus_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
async function from_candid_AIStylingConsultation_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIStylingConsultation): Promise<AIStylingConsultation> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_AppointmentStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Appointment_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Promise<Appointment> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_CustomizationVariation_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomizationVariation): Promise<CustomizationVariation> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HairstyleRecommendation_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HairstyleRecommendation): Promise<HairstyleRecommendation> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationStatus): RegistrationStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Salon_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Salon): Salon {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_StylistProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StylistProfile): Promise<StylistProfile> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIStylingConsultation]): Promise<AIStylingConsultation | null> {
    return value.length === 0 ? null : await from_candid_AIStylingConsultation_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AppointmentStatus;
    aiStylingConsultation: [] | [_AIStylingConsultation];
    userId: Principal;
    stylistId: string;
    note: [] | [string];
    createdBy: [] | [Principal];
    serviceId: string;
    dateTime: _Time;
    salonId: string;
}): Promise<{
    id: string;
    status: AppointmentStatus;
    aiStylingConsultation?: AIStylingConsultation;
    userId: Principal;
    stylistId: string;
    note?: string;
    createdBy?: Principal;
    serviceId: string;
    dateTime: Time;
    salonId: string;
}> {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n21(_uploadFile, _downloadFile, value.status),
        aiStylingConsultation: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.aiStylingConsultation)),
        userId: value.userId,
        stylistId: value.stylistId,
        note: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.note)),
        createdBy: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.createdBy)),
        serviceId: value.serviceId,
        dateTime: value.dateTime,
        salonId: value.salonId
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPhoto: _ExternalBlob;
    selectedStyles: Array<_HairstyleRecommendation>;
    aiRecommendations: Array<_HairstyleRecommendation>;
}): Promise<{
    userPhoto: ExternalBlob;
    selectedStyles: Array<HairstyleRecommendation>;
    aiRecommendations: Array<HairstyleRecommendation>;
}> {
    return {
        userPhoto: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.userPhoto),
        selectedStyles: await from_candid_vec_n27(_uploadFile, _downloadFile, value.selectedStyles),
        aiRecommendations: await from_candid_vec_n27(_uploadFile, _downloadFile, value.aiRecommendations)
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    confidenceScore: bigint;
    image: [] | [_ExternalBlob];
    styleName: string;
}): Promise<{
    description: string;
    confidenceScore: bigint;
    image?: ExternalBlob;
    styleName: string;
}> {
    return {
        description: value.description,
        confidenceScore: value.confidenceScore,
        image: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.image)),
        styleName: value.styleName
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _RegistrationStatus;
    latitude: number;
    verified: boolean;
    contactInfo: string;
    ownerName: string;
    name: string;
    longitude: number;
    address: string;
}): {
    id: string;
    status: RegistrationStatus;
    latitude: number;
    verified: boolean;
    contactInfo: string;
    ownerName: string;
    name: string;
    longitude: number;
    address: string;
} {
    return {
        id: value.id,
        status: from_candid_RegistrationStatus_n36(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        verified: value.verified,
        contactInfo: value.contactInfo,
        ownerName: value.ownerName,
        name: value.name,
        longitude: value.longitude,
        address: value.address
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.phone))
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    previewImage: [] | [_ExternalBlob];
    customizationDetails: Array<string>;
    variationName: string;
    description: string;
}): Promise<{
    previewImage?: ExternalBlob;
    customizationDetails: Array<string>;
    variationName: string;
    description: string;
}> {
    return {
        previewImage: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.previewImage)),
        customizationDetails: value.customizationDetails,
        variationName: value.variationName,
        description: value.description
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    name: string;
    specialties: Array<string>;
    photo: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    bio: string;
    name: string;
    specialties: Array<string>;
    photo?: ExternalBlob;
}> {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        specialties: value.specialties,
        photo: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    canceled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "canceled" in value ? AppointmentStatus.canceled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): RegistrationStatus {
    return "pending" in value ? RegistrationStatus.pending : "approved" in value ? RegistrationStatus.approved : "rejected" in value ? RegistrationStatus.rejected : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Promise<Array<Appointment>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Appointment_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HairstyleRecommendation>): Promise<Array<HairstyleRecommendation>> {
    return await Promise.all(value.map(async (x)=>await from_candid_HairstyleRecommendation_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Salon>): Array<Salon> {
    return value.map((x)=>from_candid_Salon_n34(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomizationVariation>): Promise<Array<CustomizationVariation>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CustomizationVariation_n44(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StylistProfile>): Promise<Array<StylistProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StylistProfile_n47(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_HairstyleRecommendation_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HairstyleRecommendation): Promise<_HairstyleRecommendation> {
    return await to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationStatus): _RegistrationStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Salon_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Salon): _Salon {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_StylistProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StylistProfile): Promise<_StylistProfile> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    name: string;
    specialties: Array<string>;
    photo?: ExternalBlob;
}): Promise<{
    id: string;
    bio: string;
    name: string;
    specialties: Array<string>;
    photo: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        specialties: value.specialties,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.photo)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
async function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    confidenceScore: bigint;
    image?: ExternalBlob;
    styleName: string;
}): Promise<{
    description: string;
    confidenceScore: bigint;
    image: [] | [_ExternalBlob];
    styleName: string;
}> {
    return {
        description: value.description,
        confidenceScore: value.confidenceScore,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.image)) : candid_none(),
        styleName: value.styleName
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: RegistrationStatus;
    latitude: number;
    verified: boolean;
    contactInfo: string;
    ownerName: string;
    name: string;
    longitude: number;
    address: string;
}): {
    id: string;
    status: _RegistrationStatus;
    latitude: number;
    verified: boolean;
    contactInfo: string;
    ownerName: string;
    name: string;
    longitude: number;
    address: string;
} {
    return {
        id: value.id,
        status: to_candid_RegistrationStatus_n10(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        verified: value.verified,
        contactInfo: value.contactInfo,
        ownerName: value.ownerName,
        name: value.name,
        longitude: value.longitude,
        address: value.address
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == RegistrationStatus.pending ? {
        pending: null
    } : value == RegistrationStatus.approved ? {
        approved: null
    } : value == RegistrationStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HairstyleRecommendation>): Promise<Array<_HairstyleRecommendation>> {
    return await Promise.all(value.map(async (x)=>await to_candid_HairstyleRecommendation_n52(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
